version: '3'

services:
  app:
    build: .
    environment:
      - DB_CONNECT=testdb
      - PORT=3000
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      -  pgdata:/var/lib/postgresql


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
